// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	inventory "github.com/harrymitchinson/dynamic-inventory-svc"
	mock "github.com/stretchr/testify/mock"
)

// HostService is an autogenerated mock type for the HostService type
type HostService struct {
	mock.Mock
}

// GetHosts provides a mock function with given fields: e
func (_m *HostService) GetHosts(e inventory.Environment) ([]inventory.Host, error) {
	ret := _m.Called(e)

	var r0 []inventory.Host
	if rf, ok := ret.Get(0).(func(inventory.Environment) []inventory.Host); ok {
		r0 = rf(e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inventory.Host)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(inventory.Environment) error); ok {
		r1 = rf(e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetHost provides a mock function with given fields: e, h
func (_m *HostService) SetHost(e inventory.Environment, h *inventory.Host) error {
	ret := _m.Called(e, h)

	var r0 error
	if rf, ok := ret.Get(0).(func(inventory.Environment, *inventory.Host) error); ok {
		r0 = rf(e, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
